Disable LTO in profile build
LTO caused a linker failure when cross-compiling for Windows:

error: linking with `x86_64-w64-mingw32-gcc` failed: exit status: 1
    = note: (...) undefined reference to
      `__imp__ZN7console5utils13STDOUT_COLORS17ha957b5b94ebd3a12E'